export const customerFields = [
  { id: "businessName", label: "Business Name", required: true },
  { id: "abn", label: "abn", required: false },
  { id: "category", label: "Category", required: true },
  { id: "subCategory", label: "SubCategory", required: true },
  { id: "description", label: "Description", required: true },
  { id: "establishedYear", label: "Established Year", required: true },
  { id: "contactPerson", label: "Contact Person" },
  { id: "phone", label: "Phone", required: true },
  { id: "email", label: "Email", required: true },
  { id: "website", label: "Website", required: false },
  {
    id: "alternateContacts.phone",
    label: "AlternateContacts Phone",
    required: false,
  },
  {
    id: "alternateContacts.email",
    label: "AlternateContacts Email",
    required: false,
  },
  { id: "address.street", label: "Address Street", required: true },
  { id: "address.suburb", label: "Address Suburb", required: true },
  { id: "address.city", label: "Address City", required: true },
  { id: "address.state", label: "Address State", required: true },
  { id: "address.postcode", label: "Address PostCode", required: true },
  { id: "longitude", label: "longitude", required: false },
  { id: "latitude", label: "latitude", required: false },
  { id: "serviceAreas", label: "Service Areas", required: true },
  { id: "monday.open", label: "Monday Open", required: false },
  { id: "monday.close", label: "Monday Close", required: false },
  { id: "tuesday.open", label: "Tuesday Open", required: false },
  { id: "tuesday.close", label: "Tuesday Close", required: false },
  { id: "wednesday.open", label: "Wednesday Open", required: false },
  { id: "wednesday.close", label: "Wednesday Close", required: false },
  { id: "thursday.open", label: "Thursday Open", required: false },
  { id: "thursday.close", label: "Thursday Close", required: false },
  { id: "friday.open", label: "Friday Open", required: false },
  { id: "friday.close", label: "Friday Close", required: false },
  { id: "saturday.open", label: "Saturday Open", required: false },
  { id: "saturday.close", label: "Saturday Close", required: false },
  { id: "sunday.open", label: "Sunday Open", required: false },
  { id: "sunday.close", label: "Sunday Close", required: false },
  { id: "publicHolidayNotes", label: "Public Holiday Notes", required: false },
  { id: "is24x7", label: "is24x7", required: false },
  { id: "logoUrl", label: "LogoUrl", required: false },
  { id: "gallery", label: "Gallery", required: false },
  { id: "introVideo", label: "Intro Video", required: false },
  { id: "facebook", label: "Facebook", required: false },
  { id: "instagram", label: "Instagram", required: false },
  { id: "linkedin", label: "Linkedin", required: false },
  { id: "others", label: "Others", required: false },
  { id: "services", label: "Services", required: true },
  { id: "keywords", label: "Keywords", required: false },
  { id: "paymentMethods", label: "Payment Methods", required: false },
  { id: "certifications", label: "Certifications", required: false },
  { id: "promotions", label: "Promotions", required: false },
  { id: "status", label: "Status", required: false },
  { id: "isFeature", label: "isFeature", required: false },
  { id: "popular", label: "Popular", required: false },
];
